general:
  project_name: scembed_test_spatial_2
  mamba_env: scembed
  entity: spatial_vi
  modules: stack eth_proxy
  count: 1

slurm:
  time: "01:00:00"
  mem_per_cpu: "32G"
  job_name: scembed_resolvi
  output: slurm_logs/resolvi_%A_%a.out
  array: "0-3"
  gpus: rtx_4090:1

wandb:
  program: train.py
  method: grid
  name: resolvi
  metric:
    goal: maximize
    name: scib_total_score
  parameters:
    method:
      value: resolvi
    semisupervised:
      values: [true, false]
    max_epochs:
      values: [20, 40]
