general:
  project_name: sweep_test
  mamba_env: py312
  entity: spatial_vi
  modules: stack eth_proxy

slurm:
  time: "00:30:00"
  mem_per_cpu: "8G"
  job_name: sweep
  output: slurm_logs/wandb_grid_%A_%a.out
  array: "0-2"

wandb:
  program: train.py
  method: grid
  name: sweep

  metric:
    goal: maximize
    name: val_acc
  parameters:
    batch_size:
      values: [16,32,64]
    lr:
      values: [0.001, 0.01]
    epochs:
      values: [5, 10, 15]
